name: Android Gradle Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31.0.0'

      - name: Build project
        run: ./gradlew build

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
